stages:
  - build
  - test
  - publish
  - unpublish
  - tag
  - unpack

workflow:
  name: "systemd-$REPO-$RELEASE-$SOURCE"
  rules:
    - if: $DO_SKIP_ALL == "true" # this variable may be set in mn:autorelease job
      when: never
    - when: always

.fedora:
  image: quay.io/fedora/fedora:latest
  before_script:
    # verify important variables
    - test -n "$CENTOS_CERT"
    - test -n "$REPO"; echo "$REPO"
    - test -n "$RELEASE"; echo "$RELEASE"
    - test -n "$SOURCE"; echo "$SOURCE"
    - test -n "$DO_PUBLISH"; echo "$DO_PUBLISH"
    - test -n "$DO_TEST"; echo "$DO_TEST"
    - test -n "$DO_UNPACK"; echo "$DO_UNPACK"
    - export DRY_RUN=$(test "$DO_DRY_RUN" == "true" && echo "--dry-run" || echo "--no-dry-run"); echo "$DRY_RUN"; test -n "$DRY_RUN"
    - env

    # install necessary packages
    - dnf --quiet install -y tar git-core python3 centos-packager mock mock-centos-sig-configs

###################################################
# BUILD
###################################################
systemd:build:
  stage: build
  extends: .fedora
  script:
    - export SCRATCH=$(test "$DO_PUBLISH" == "false" && echo "--scratch" || echo "--no-scratch"); echo "$SCRATCH"; test -n "$SCRATCH"
    - export RPM_EXTRA_INFO=$(test "$DO_RPM_EXTRA_INFO" == "true" && echo "--rpm-extra-info=mr${CI_MERGE_REQUEST_IID}"); echo "$RPM_EXTRA_INFO"
    - ./releng.py $DRY_RUN --cert "$CENTOS_CERT" build --repo "$REPO" --release "$RELEASE" --source "$SOURCE" $SCRATCH $RPM_EXTRA_INFO
  rules:
    - when: always
  interruptible: true
  artifacts:
    paths: [ 'artifacts/*-task-id.txt' ]

###################################################
# TEST
###################################################
systemd:test:
  stage: test
  image: quay.io/testing-farm/cli:latest
  dependencies:
    - systemd:build
  before_script:
    - export TASK_ID=$(find . -name "*-task-id.txt" -exec cat {} \; -quit); echo "$TASK_ID"; test -n "$TASK_ID"
  script:
    - testing-farm request --git-ref $CI_MERGE_REQUEST_REF_PATH --git-url $CI_MERGE_REQUEST_PROJECT_URL --compose "Fedora-41"
      --environment MKOSI_DISTRIBUTION=centos --environment MKOSI_RELEASE=$RELEASE --environment CBS_TASK_ID=$TASK_ID
      --environment MKOSI_REPOSITORIES=hyperscale-packages-main --plan plans/upstream --no-wait > request.output
    - export REQUEST_ID=$(grep api request.output | awk -F/ '{ print $NF }'); test -n "$REQUEST_ID"; echo "$REQUEST_ID"
    - echo "$REQUEST_ID" > request.id
    - testing-farm watch --id "$REQUEST_ID"
  after_script:
    - export REQUEST_ID=$(cat request.id); echo "$REQUEST_ID"
    - test "$CI_JOB_STATUS" == "canceled" && test -n "$REQUEST_ID" && testing-farm cancel "$REQUEST_ID" || /bin/true
  rules:
    - if: $DO_TEST == 'allow_failure'
      allow_failure: true
    - if: $DO_TEST == 'true'
      allow_failure: false
  interruptible: true

###################################################
# PUBLISH
###################################################
.publish:
  stage: publish
  extends: .fedora
  dependencies:
    - systemd:build
  script:
    - export TASK_ID=$(find . -name "*-task-id.txt" -exec cat {} \; -quit); echo "$TASK_ID"; test -n "$TASK_ID"
    - export PUBLISH_REPO=$(test "$DO_PUBLISH" == "release" && echo "release" || echo "testing"); echo "$PUBLISH_REPO"; test -n "$PUBLISH_REPO"
    - ./releng.py $DRY_RUN --cert "$CENTOS_CERT" publish --repo "$REPO" --release "$RELEASE" --task-id "$TASK_ID" --publish-repo "$PUBLISH_REPO"
  interruptible: true

systemd:publish:
  extends: .publish
  rules:
    - if: $DO_PUBLISH != 'false'
  artifacts:
    paths: [ 'artifacts/*-tag.txt' ]

systemd:publish:dry-run:
  extends: .publish
  variables:
    DO_DRY_RUN: 'true'
  rules:
    - if: $DO_PUBLISH_DRY_RUN == 'true'
    - if: $DO_PUBLISH_DRY_RUN == 'no-wait'
      needs: [ 'systemd:build' ] # allows proceeding without waiting previous steps

###################################################
# UNPUBLISH
###################################################
.unpublish:
  stage: unpublish
  extends: .fedora
  script:
    - export PUBLISH_REPO=$(test "$DO_PUBLISH" == "release" && echo "release" || echo "testing"); echo "$PUBLISH_REPO"; test -n "$PUBLISH_REPO"
    - export LATEST_N=$(test "$DO_PUBLISH" == "release" && echo "30" || echo "7"); echo "$LATEST_N"; test -n "$LATEST_N"
    - ./releng.py $DRY_RUN --cert "$CENTOS_CERT" unpublish --repo "$REPO" --release "$RELEASE" --publish-repo "$PUBLISH_REPO" --latest-n "$LATEST_N"
  interruptible: true

systemd:unpublish:
  extends: .unpublish
  rules:
    - if: $DO_UNPUBLISH == 'true'
      allow_failure: true

systemd:unpublish:dry-run:
  extends: .unpublish
  variables:
    DO_DRY_RUN: 'true'
  rules:
    - if: $DO_UNPUBLISH_DRY_RUN == 'true'
    - if: $DO_UNPUBLISH_DRY_RUN == 'no-wait'
      needs: [ 'systemd:build' ] # allows proceeding without waiting previous steps

###################################################
# TAG
###################################################
systemd:tag:
  stage: tag
  dependencies:
    - systemd:publish
  before_script:
    - env # Show variables that were passed to the job
  script:
    - export GIT_TAG=$(find . -name "*-tag.txt" -exec cat {} \; -quit); echo "$GIT_TAG"; test -n "$GIT_TAG"
    - git remote set-url origin "https://hyperscalebot:${GIT_PUSH_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
    - git config user.email "hyperscalebot@example.com"
    - git config user.name "hyperscalebot"
    - git tag "$GIT_TAG"
    - git push origin tag "$GIT_TAG"
  rules:
    - if: $DO_PUBLISH == 'release'
  interruptible: false # tagging should complete if results are published

###################################################
# UNPACK
###################################################
.unpack:
  stage: unpack
  extends: .fedora
  dependencies:
    - systemd:build
  script:
    - export TASK_ID=$(find . -name "*-task-id.txt" -exec cat {} \; -quit); echo "$TASK_ID"; test -n "$TASK_ID"
    - ./releng.py $DRY_RUN unpack --repo "$REPO" --release "$RELEASE" --task-id "$TASK_ID"
  interruptible: true

systemd:unpack:
  extends: .unpack
  rules:
    - if: $DO_UNPACK == 'true'
      allow_failure: false
    - if: $DO_UNPACK == 'manual'
      when: manual
      allow_failure: true # this is necessary to let pipeline completing without waiting for this job
      needs: [ 'systemd:build' ] # allows proceeding without waiting previous steps

systemd:unpack:dry-run:
  extends: .unpack
  variables:
    DO_DRY_RUN: "true"
  rules:
    - if: $DO_UNPACK_DRY_RUN == 'true'
    - if: $DO_UNPACK_DRY_RUN == 'no-wait'
      needs: [ 'systemd:build' ] # allows proceeding without waiting previous steps
