stages:
  - build
  - test
  - publish
  - tag
  - unpack

workflow:
  name: "systemd-$REPO-$RELEASE-$SOURCE"
  rules:
    - if: $DO_SKIP_ALL == "true" # this variable may be set in mn:autorelease job
      when: never
    - when: always

.fedora:
  image: quay.io/fedora/fedora:latest
  before_script:
    # verify important variables
    - test -n "$CENTOS_CERT"
    - test -n "$REPO"; echo "$REPO"
    - test -n "$RELEASE"; echo "$RELEASE"
    - test -n "$SOURCE"; echo "$SOURCE"
    - test -n "$DO_PUBLISH"; echo "$DO_PUBLISH"
    - test -n "$DO_TEST"; echo "$DO_TEST"
    - test -n "$DO_UNPACK"; echo "$DO_UNPACK"
    - env

    # install necessary packages
    - dnf --quiet install -y tar git-core python3 centos-packager mock mock-centos-sig-configs

systemd:build:
  stage: build
  extends: .fedora
  script:
    - export SCRATCH=$(test "$DO_PUBLISH" == "false" && echo "--scratch" || echo "--no-scratch"); echo $SCRATCH; test -n "$SCRATCH"
    - export RPM_EXTRA_INFO=$(test "$DO_RPM_EXTRA_INFO" == "true" && echo "--rpm-extra-info=mr${CI_MERGE_REQUEST_IID}"); echo "$RPM_EXTRA_INFO"
    - ./releng.py --cert "$CENTOS_CERT" build --repo "$REPO" --release "$RELEASE" --source "$SOURCE" $SCRATCH $RPM_EXTRA_INFO
  rules:
    - when: always
  interruptible: true
  artifacts:
    paths: [ 'artifacts/*-task-id.txt' ]

systemd:test:
  stage: test
  image: quay.io/testing-farm/cli:latest
  dependencies:
    - systemd:build
  before_script:
    - export TASK_ID=$(find . -name "*-task-id.txt" -exec cat {} \; -quit); echo "$TASK_ID"; test -n "$TASK_ID"
  script:
    - testing-farm request --git-ref $CI_MERGE_REQUEST_REF_PATH --git-url $CI_MERGE_REQUEST_PROJECT_URL --compose "Fedora-41"
      --environment MKOSI_DISTRIBUTION=centos --environment MKOSI_RELEASE=$RELEASE --environment CBS_TASK_ID=$TASK_ID
      --environment MKOSI_REPOSITORIES=hyperscale-packages-main --plan plans/upstream --no-wait > request.output
    - export REQUEST_ID=$(grep api request.output | awk -F/ '{ print $NF }'); test -n "$REQUEST_ID"; echo "$REQUEST_ID"
    - echo "$REQUEST_ID" > request.id
    - testing-farm watch --id $REQUEST_ID
  after_script:
    - export REQUEST_ID=$(cat request.id); echo $REQUEST_ID
    - test "$CI_JOB_STATUS" == "canceled" && test -n "$REQUEST_ID" && testing-farm cancel "$REQUEST_ID" || /bin/true
  rules:
    - if: $DO_TEST == 'allow_failure'
      allow_failure: true
    - if: $DO_TEST == 'true'
      allow_failure: false
  interruptible: true

systemd:publish:
  stage: publish
  extends: .fedora
  dependencies:
    - systemd:build
  script:
    - export TASK_ID=$(find . -name "*-task-id.txt" -exec cat {} \; -quit); echo "$TASK_ID"; test -n "$TASK_ID"
    - ./releng.py --cert "$CENTOS_CERT" publish --repo "$REPO" --release "$RELEASE" --task-id "$TASK_ID" --publish-repo "$DO_PUBLISH"
  rules:
    - if: $DO_PUBLISH != 'false'
  interruptible: true
  artifacts:
    paths: [ 'artifacts/*-tag.txt' ]

systemd:tag:
  stage: tag
  dependencies:
    - systemd:publish
  before_script:
    - env # Show variables that were passed to the job
  script:
    - export GIT_TAG=$(find . -name "*-tag.txt" -exec cat {} \; -quit); echo "$GIT_TAG"; test -n "$GIT_TAG"
    - git remote set-url origin "https://hyperscalebot:${GIT_PUSH_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
    - git config user.email "hyperscalebot@example.com"
    - git config user.name "hyperscalebot"
    - git tag "$GIT_TAG"
    - git push origin tag "$GIT_TAG"
  rules:
    - if: $DO_PUBLISH == 'release'
  interruptible: false # tagging should complete if results are published

systemd:unpack:
  stage: unpack
  extends: .fedora
  dependencies:
    - systemd:build
  script:
    - export TASK_ID=$(find . -name "*-task-id.txt" -exec cat {} \; -quit); echo "$TASK_ID"; test -n "$TASK_ID"
    - ./releng.py unpack --repo "$REPO" --release "$RELEASE" --task-id "$TASK_ID"
  rules:
    - if: $DO_UNPACK == 'true'
      allow_failure: false
    - if: $DO_UNPACK == 'manual'
      when: manual
      allow_failure: true # this is necessary to let pipeline completing without waiting for this job
  interruptible: true
