stages:
  - build
  - test
  - publish
  - tag

workflow:
  name: "systemd-$REPO-$RELEASE-$SOURCE"

default:
  interruptible: true

.fedora:
  image: quay.io/fedora/fedora:latest

systemd:build:
  stage: build
  extends: .fedora
  script:
    - sleep 300
    - /bin/false
  rules:
    - when: always
  artifacts:
    paths: [ 'artifacts/*-task-id.txt' ]

systemd:test:
  stage: test
  image: quay.io/testing-farm/cli:latest
  dependencies:
    - systemd:build
  before_script:
    - test -n "$REPO"; echo "$REPO"
    - test -n "$RELEASE"; echo "$RELEASE"
    - export TASK_ID=$(find . -name "*-task-id.txt" -exec cat {} \; -quit); echo "$TASK_ID"; test -n "$TASK_ID"
  script:
    - testing-farm request --git-ref $CI_MERGE_REQUEST_REF_PATH --git-url $CI_MERGE_REQUEST_PROJECT_URL --compose 'Fedora-Rawhide'
      --environment REPO=$REPO --environment RELEASE=$RELEASE --environment TASK_ID=$TASK_ID --plan plans/gitlab-ci
      --no-wait > request.output
    - export REQUEST_ID=$(grep api request.output | awk -F/ '{ print $NF }'); test -n "$REQUEST_ID"; echo "$REQUEST_ID"
    - echo "$REQUEST_ID" > request.id
    - testing-farm watch --id $REQUEST_ID
  after_script:
    - export REQUEST_ID=$(cat request.id); echo $REQUEST_ID
    - test "$CI_JOB_STATUS" == "canceled" && test -n "$REQUEST_ID" && testing-farm cancel "$REQUEST_ID"
  rules:
    - if: $DO_TEST == 'true'

systemd:publish:
  stage: publish
  extends: .fedora
  dependencies:
    - systemd:build
  script:
    - test -n "$DO_PUBLISH"; echo "$DO_PUBLISH"
    - export TASK_ID=$(find . -name "*-task-id.txt" -exec cat {} \; -quit); echo "$TASK_ID"; test -n "$TASK_ID"
    - ./releng.py --cert $CENTOS_CERT --repo $REPO --release $RELEASE publish --task-id $TASK_ID --publish-repo $DO_PUBLISH
  rules:
    - if: $DO_PUBLISH != 'false'

  artifacts:
    paths: [ 'artifacts/*-tag.txt' ]

systemd:tag:
  stage: tag
  dependencies:
    - systemd:publish
  before_script:
    - env # Show variables that were passed to the job
  script:
    - export GIT_TAG=$(find . -name "*-tag.txt" -exec cat {} \; -quit); echo "$GIT_TAG"; test -n "$GIT_TAG"
    - git remote set-url origin "https://gitlab-ci-token:${GIT_PUSH_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
    - git config user.email "ci-bot@example.com"
    - git config user.name "ci-bot"
    - git tag "$GIT_TAG"
    - git push origin tag "$GIT_TAG"
  rules:
    - if: $DO_PUBLISH == 'release'
