variables:
  # if adding/changing variables don't forget to update the list in mn:autorelease job
  SOURCE:
    description: "Do build using upstream HEAD. Otherwise use sources from systemd.spec"
    options: ["head", "spec"]
    value: "head"
  DO_PUBLISH:
    description: "Publish result to 'release' or 'testing' CBS repo. If false, don't publish"
    options: ["false", "testing", "release"]
    value: "false"
  DO_TEST:
    description: "Setting 'false' avoids running tests (useful when testing-farm is unstable). Setting 'allow_failure' runs tests but continue pipeline execution when test fails."
    options: ["true", "false", "allow_failure"]
    value: "true"
  DO_UNPACK:
    description: "If 'true', unpacks built src.rpm into https://gitlab.com/CentOS/Hyperscale/rpms-unpacked/systemd. Setting to 'false' disables this. 'manual' creates a step in CI which one can manually run."
    options: ["true", "false", "manual"]
    value: "true"
  DO_AUTORELEASE:
    description: "If 'true', CI runs an extra step to potentially increment release_override and upload new tarbal to lookaside cache. No-op if no such action is necessary. This setting works only when SOURCE=spec and DO_PUBLISH=release. Useful setting to 'false' when doing a bugfix for an old release (eg: 257.10 when there is already 258)"
    options: ["true", "false"]
    value: "true"

stages:
  - prepare
  - setup

.matrix2:
  parallel:
    matrix:
      - REPO: facebook
        RELEASE: ["9_z", "10_z"]
      - REPO: main
        RELEASE: ["9", "10"]

.matrix3:
  parallel:
    matrix:
      - REPO: facebook
        RELEASE: ["9_z", "10_z"]
        SOURCE: [head, spec]
      - REPO: main
        RELEASE: ["9", "10"]
        SOURCE: [head, spec]

# setup for merge request
mr:
  stage: setup
  variables:
    # REPO, RELEASE, SOURCE come from matrix
    DO_TEST: "true"
    DO_UNPACK: "manual"
    DO_PUBLISH: "false"
    DO_UNPUBLISH: "false"
    DO_RPM_EXTRA_INFO: "true"
    DO_PUBLISH_DRY_RUN: "no-wait"
    DO_UNPUBLISH_DRY_RUN: "no-wait"
    DO_UNPACK_DRY_RUN: "no-wait"
  trigger:
    include: .gitlab-child-ci.yml
    strategy: depend
    forward:
      # false is default, but make it clear: no pipelines vars should be forwarded
      pipeline_variables: false
  interruptible: true # cancel child pipelines when parent cancelled
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  extends: .matrix3

# setup for nightly builds
ni:
  stage: setup
  variables:
    # REPO, RELEASE come from matrix
    SOURCE: "head"
    DO_TEST: "allow_failure"
    DO_UNPACK: "true"
    DO_PUBLISH: "testing"
    DO_UNPUBLISH: "true"
  trigger:
    include: .gitlab-child-ci.yml
    strategy: depend
    forward:
      # false is default, but make it clear: no pipelines vars should be forwarded
      pipeline_variables: false
  interruptible: true # cancel child pipelines when parent cancelled
  rules:
    - if: $CI_PIPELINE_SOURCE == 'schedule'
  extends: .matrix2

# setup for manual (release) run
mn:autorelease:
  stage: prepare
  image: quay.io/fedora/fedora:latest
  before_script:
    - test -n "$CENTOS_CERT"
    - ln --symbolic --force "$CENTOS_CERT" ~/.centos.cert  # centos-lookaside-upload-sig has this path hardcoded
    - env
    - dnf --quiet install -y git-core python3 centos-packager
  script:
    # mn:autorelease job works in a special way
    # 1. ./releng.py autorelease produces no changes to commit, the execution continues as normal
    # 2. if there are changes to commit, the job creates a commit and pushes it in a special way
    #    using '-o ci.variable="FOO=BAR"'. The DO_AUTORELEASE=true variable triggers another
    #    pipeline whiche uses commited changes to actually perform a build.

    # autorelease logic
    # It only make sense to run it with  $SOURCE == 'spec' && $DO_PUBLISH == 'release'
    # which are checked in the 'rules'
    - ./releng.py autorelease

    # early exit if nothing to commit
    - git diff --exit-code systemd.spec sources && exit 0 || /bin/true

    # commit
    - test -n "$GIT_PUSH_TOKEN"
    - test -s git-commit-message.txt # file exists and not empty
    - git remote set-url origin "https://hyperscalebot:${GIT_PUSH_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
    - git config user.email "hyperscalebot@example.com"
    - git config user.name "hyperscalebot"
    - git add systemd.spec sources
    - git commit -F git-commit-message.txt
    - 'git push origin HEAD:$CI_COMMIT_REF_NAME
        -o ci.variable="SOURCE=$SOURCE"
        -o ci.variable="DO_PUBLISH=$DO_PUBLISH"
        -o ci.variable="DO_TEST=$DO_TEST"
        -o ci.variable="DO_UNPACK=$DO_UNPACK"
        -o ci.variable="DO_AUTORELEASE=false"' # magical variable to trigger only mn:setup in forked pipeline

    # notify child pipeline to do nothing.
    - echo 'SKIP_ALL=true' > autorelease.env

    # human friendly message
    - echo "FORKING ANOTHER PIPELINE! Check ${CI_PROJECT_URL}/pipelines, search for a new pipeline with the following message:"
    - cat git-commit-message.txt
  interruptible: true # cancel child pipelines when parent cancelled
  artifacts:
    reports:
      dotenv: autorelease.env
  rules:
    - if: $CI_PIPELINE_SOURCE == 'web' && $SOURCE == 'spec' && $DO_PUBLISH == 'release' && $DO_AUTORELEASE == 'true'

mn:setup:
  stage: setup
  variables:
    # REPO, RELEASE come from matrix
    # SOURCE, DO_TEST, DO_PUBLISH come from pipeline vars

    # mn:autorelease sets this variable, but we propagate it to child pipeline..
    # Unfortunatelly, variables sets via artifacts:reports:dotenv can't be used in 'rules'
    DO_SKIP_ALL: $SKIP_ALL
  trigger:
    include: .gitlab-child-ci.yml
    strategy: depend
    forward:
      pipeline_variables: true
  interruptible: true # cancel child pipelines when parent cancelled
  rules:
    - if: $CI_PIPELINE_SOURCE == 'web' # run only for pipelines started via gitlab web-interface (usually a release)
    - if: $CI_PIPELINE_SOURCE == 'parent_pipeline' && $DO_AUTORELEASE == 'false' # special condition set in mn:autorelease job
  extends: .matrix2
