variables:
  # don't reference these variables in the child pipelines because they reset to default values
  SOURCE_VAR:
    description: "Do build using upstream HEAD. Otherwise use sources from systemd.spec"
    options: ["head", "spec"]
    value: "head"
  PUBLISH_VAR:
    description: "Publish result to 'release' or 'testing' CBS repo. If false, don't publish"
    options: ["false", "testing", "release"]
    value: "false"
  DO_TEST_VAR:
    description: "If set to false, allows to avoid running tests (useful when testing-farm is unstable)"
    options: ["true", "false"]
    value: "true"

stages:
  - setup

.matrix2:
  parallel:
    matrix:
      - REPO: [main, facebook]
        RELEASE: [9, 10]

.matrix3:
  parallel:
    matrix:
      - REPO: [main, facebook]
        RELEASE: [9, 10]
        SOURCE: ['head', 'spec']

# setup for merge request
mr:
  stage: setup
  variables:
    # REPO, RELEASE, SOURCE come from matrix
    DO_TEST: "true"
    DO_PUBLISH: "false"
  trigger:
    include: .gitlab-child-ci.yml
    strategy: depend
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  extends: .matrix3

# setup for nightly builds
ni:
  stage: setup
  variables:
    # REPO, RELEASE come from matrix
    SOURCE: "head"
    DO_TEST: "false"
    DO_PUBLISH: "testing"
  trigger:
    include: .gitlab-child-ci.yml
    strategy: depend
  rules:
    - if: $CI_PIPELINE_SOURCE == 'schedule'
  extends: .matrix2

# setup for manual run
mn:
  stage: setup
  variables:
    # REPO, RELEASE come from matrix
    SOURCE: $SOURCE_VAR # child pipeline receive default value otherwise
    DO_TEST: $DO_TEST_VAR
    DO_PUBLISH: $PUBLISH_VAR
  trigger:
    include: .gitlab-child-ci.yml
    strategy: depend
  rules:
    - if: $CI_PIPELINE_SOURCE == 'web'
  extends: .matrix2
