[Config]
MinimumVersion=25~devel

[Distribution]
Distribution=centos

[Output]
OutputDirectory=mkosi.output

[Content]
Bootable=no
Autologin=yes

Packages=
        acl
        attr
        bash-completion
        binutils
        bpftrace
        coreutils
        curl
        diffutils
        dnf
        findutils
        gdb
        git-core
        grep
        gzip
        iproute
        iproute-tc
        iputils
        jq
        kbd
        kmod
        less
        man
        man-db
        nano
        nftables
        nmap-ncat
        openssh-clients
        openssh-server
        openssl
        p11-kit
        pam
        passwd
        pciutils
        perf
        policycoreutils
        polkit
        procps-ng
        python3
        rpm
        rpm-build
        rsync
        sed
        setools-console
        socat
        strace
        stress-ng
        tar
        tmux
        tree
        util-linux
        valgrind
        vim-common
        which
        zsh
        zstd
        NetworkManager

VolatilePackages=
        kernel-core
        selinux-policy
        selinux-policy-targeted
        systemd
        systemd-boot
        systemd-container
        systemd-devel
        systemd-journal-remote
        systemd-libs
        systemd-pam
        systemd-resolved
        systemd-udev

InitrdVolatilePackages=
        systemd
        systemd-libs
        systemd-udev

SELinuxRelabel=yes

[Build]
ToolsTree=default
BuildDirectory=mkosi.builddir
CacheDirectory=mkosi.cache
Incremental=yes
BuildSources=.
BuildSourcesEphemeral=yes

[Runtime]
RuntimeBuildSources=yes
RuntimeScratch=no
CPUs=2
RAM=4G
TPM=no
VSock=yes
KVM=yes
KernelCommandLineExtra=
        systemd.log_level=debug,console:info
        systemd.log_ratelimit_kmsg=0
        # Disable the kernel's ratelimiting on userspace logging to kmsg.
        printk.devkmsg=on
        systemd.early_core_pattern=/core
        systemd.firstboot=no
        raid=noautodetect
        psi=1
