[Match]
Distribution=centos

[Distribution]
Mirror=https://mirror.stream.centos.org/
Release=10

[Build]
ToolsTreeDistribution=centos
ToolsTreeRelease=%r
ToolsTreeRepositories=hyperscale-packages-main
Environment=EPEL_MIRROR=https://dl.fedoraproject.org/pub

[Content]
Packages=centos-release-hyperscale
